### ISSUE TITLE
地下城进度逻辑判断

### ISSUE THREAD

**Issue by ID44977** [smartgrass/AutoPcr#1]
首先感谢该项目，确实挺方便。。
为了适配我自己蓝叠模拟器所以重新截了图，然后发现如果按照正常流程走一遍没啥问题。
但如果已经进入地下城或者当日地下城已经打完的情况下执行该脚本，EnterDxc()和DxcFristFight()顺序执行然后就是漫长的win lose判断。
既然EnterDxc()有bool返回，判断True再进FirstFight感觉适合多种情况。

**Comment by smartgrass** [comment]
有了自动脚本后, 已经不会手动去打地下城了 ,main函数开头执行的StartDxc(1) 表示的就是从地下城第一关开始 .如果有调试需要就直接修改上面的数字就可以了. 因为很少用到, 进度判断就懒得做了

**Comment by smartgrass** [comment]
> 首先感谢该项目，确实挺方便。。 为了适配我自己蓝叠模拟器所以重新截了图，然后发现如果按照正常流程走一遍没啥问题。 但如果已经进入地下城或者当日地下城已经打完的情况下执行该脚本，EnterDxc()和DxcFristFight()顺序执行然后就是漫长的win lose判断。 既然EnterDxc()有bool返回，判断True再进FirstFight感觉适合多种情况。

有了自动脚本后, 已经不会手动去打地下城了 ,main函数开头执行的StartDxc(1) 表示的就是从地下城第一关开始 .如果有调试需要就直接修改上面的数字就可以了. 因为很少用到, 进度判断就懒得做了

**Comment by ID44977** [comment]
> 

嗯，我自己这边加了点判断的功能，感觉以后全自动也不用这么细致了哈哈。
话说没怎么研究过图片识别，适配其他模拟器以及提高本机运行识别准确度我现在是通过给本地分辨率DPI全部重新截图来实现的，感觉有点麻烦。。。（蓝叠模拟器，720P，240DPI）
