### ISSUE TITLE
有看到领取公会体力的图标，任务在哪里设置

### ISSUE THREAD

**Issue by duoshoumiao** [smartgrass/AutoPcr#18]
![IMG_20230911_003114.jpg](https://github.com/smartgrass/AutoPcr/assets/94856184/7df9e338-9bf6-4a37-8565-294ff19ab105)

**Comment by smartgrass** [comment]
勾上领取奖励就可以, 任务会一起领, 一般不需要设置吧?

**Comment by duoshoumiao** [comment]
> 勾上领取奖励就可以, 任务会一起领, 一般不需要设置吧?

我第一次用试了一下那个领取奖励，看它只做了领取邮件跟任务以为没有公会小屋。

**Comment by smartgrass** [comment]
下次再试试吧 如果是图片识别不到就手动换下图片

**Comment by duoshoumiao** [comment]
换了图可以了 。又发现一个问题就是，如果体力不足，就变只买体力不打任务，因为它把买体力当成任务了，比如💔本，如果清过一次了，下次去变成买次数但不打。
