### ISSUE TITLE
关于地下城在非双倍期间使用

### ISSUE THREAD

**Issue by KNBLG** [smartgrass/AutoPcr#2]
非常感谢能制作这个自动化脚本，地下城在没有双倍的时候很多人都是存一次地下城次数，可以的话能否可以判断一下如果地下城还有剩余次数就直接进入但是不打这次地下城保留一次地下城次数（或者直接进一下最后一个地下城）。还有关于工会点赞这个可以的话非常希望实装一下（建议可以点两个赞因为有可能出现单个人工会，一个人点赞次数过多不允许点赞的情况。）

**Comment by smartgrass** [comment]
做一个自动化脚本真没考虑做这么细致的...
