### ISSUE TITLE
中文路径/权限问题

### ISSUE THREAD

**Issue by fxxkojbk** [smartgrass/AutoPcr#21]
我按照设置设置好了 却没什么用
![image](https://github.com/smartgrass/AutoPcr/assets/133769367/3b6022a9-00e1-4bc8-a095-cd6cc230414a)

**Comment by smartgrass** [comment]
权限问题吧, 换d盘试试, 还有文件夹不要带中文

**Comment by fxxkojbk** [comment]
换了就好了
