### ISSUE TITLE
temp只能截图到雷电的启动画面->[混显相关]

### ISSUE THREAD

**Issue by BakaCookie** [smartgrass/AutoPcr#24]
![temp](https://github.com/smartgrass/AutoPcr/assets/90391333/5436a7ba-b392-4eee-8aa9-eb2668626d66)
然后就一直显示识别不到

**Comment by smartgrass** [comment]
看运行失败原因.txt里写的, 和混显有关系 -> https://www.bilibili.com/opus/828638421363720201
