### ISSUE TITLE
老师我想问一下地下城这里是怎么设置的

### ISSUE THREAD

**Issue by orrangee** [smartgrass/AutoPcr#4]
![T)NN_4Z55JA@$@_{72S`Z@P](https://user-images.githubusercontent.com/104009963/175510103-f5e370b2-5d8e-4b60-ba9b-5a3f25d250dc.png)

**Comment by smartgrass** [comment]
最近刚做好的功能, 还有些bug,先别用它吧.

**Comment by orrangee** [comment]
> 最近刚做好的功能, 还有些bug,先别用它吧.

 好的老师
