### ISSUE TITLE
64位雷电模拟器因为窗体标题不对无法识别

### ISSUE THREAD

**Issue by cpms** [smartgrass/AutoPcr#5]
![image](https://user-images.githubusercontent.com/4178287/186562445-2af24518-89a6-40d9-b1ec-28b08df3d76f.png)

![image](https://user-images.githubusercontent.com/4178287/186562162-91294e73-c6cc-4cfd-8bb6-3a1a3555c6c9.png)
建议增加一个选项，让用户选择模拟器的版本

**Comment by smartgrass** [comment]
雷电模拟器的多开器应该可以改名字的, 见文件夹->\AutoPcr_py\扩展功能说明\使用小号

**Comment by cpms** [comment]
> 

![image](https://user-images.githubusercontent.com/4178287/186821206-3ae8387d-885e-4549-83e5-e1b05b7d4c73.png)
名字就是正常的名字，64位模拟器的标题会自动加上(64)，无法去掉

**Comment by smartgrass** [comment]
> 

嗯嗯,，感谢建议。已经加上64位的选项了
![QQ截图20220826130628](https://user-images.githubusercontent.com/30657539/186826347-18e2e7ec-b1d0-4a41-9521-237994caeacc.png)
